### ISSUE TITLE
Sections should cover link colours

### ISSUE THREAD

**Issue by honzapara** [digitalnsw/nsw-design-system#184]
Hello,

first of all, you did the amazing job by reformatting the design system in version 3!
I'm currently implementing it to our Drupal theme and actually a little improvement would be helpful. 

`nsw-section` should also handle the dark colour of links on the dark variants. Currently it covers only the colour of text elements.

See src/core/section/_section.scss
```
  @each $name, $variant in $nsw-sections {
    &--#{$name} {
      background-color: map-get($variant, background);
      color: map-get($variant, color);
    }
  }
```

**Comment by tjharrop** [comment]
Hi @honzapara - thanks for this! We'll be including it in a new patch version soon

**Comment by tjharrop** [comment]
Hi @honzapara - this will be included in the next patch release. Thanks for your help with it :)

**Comment by anna-yeshtukova** [comment]
Hi @honzapara. This issue have been fixed by introducing new utility class `nsw-section--invert`. It inverts link colours and ensure that all components display correctly on dark coloured backgrounds. You can read more about it [here](https://digitalnsw.github.io/nsw-design-system/core/section/index.html).
