### ISSUE TITLE
Guidance for profile icon in header or main nav

### ISSUE THREAD

**Issue by eschweitzer78** [digitalnsw/nsw-design-system#312]
Team I am seeking your guidance with respect to the addition of a profile icon (and language selector) in the upper part of the page -- including responsiveness.

At the moment the recommended blueprint for the header on mobile is as follows:
<img width="641" alt="image" src="https://github.com/digitalnsw/nsw-design-system/assets/20468027/5e4c8a1a-ce02-4154-a26a-5493e29f9acd">

on desktop:
<img width="1006" alt="image" src="https://github.com/digitalnsw/nsw-design-system/assets/20468027/d3bcc0b9-393f-4777-858d-7faa4cafd7d3">

My NSW Government customer requires the addition of a profile icon (with a dropdown menu) to log out, see/edit the user profile etc. A language selection bar might be required at some stage too:

[nsw.gov.au](https://nsw.gov.au) features these as illustrated below
on mobile (notice how the Waratah logo is moved towards the left of the screen to leave room):
<img width="836" alt="image" src="https://github.com/digitalnsw/nsw-design-system/assets/20468027/c1a99743-24ca-4769-8383-74f1ccbf7b17">

on desktop:
<img width="1277" alt="image" src="https://github.com/digitalnsw/nsw-design-system/assets/20468027/51eadf34-2948-4a75-8508-ea6bb76b16f3">

Are these acceptable and would you further endorse them as the way for similar items that don't feel home in the nav bar? The UX designer seems to imply that the header should remain devoid of any addition and that the profile menu etc. should be placed in main nav area but on the right hand side but that doesn't sound quite right.

Side question: is the Waratah logo with Government in the label acceptable on mobile vs. the suggested blueprint which only has NSW (without Government)?

Thanks heaps

**Comment by JamesDPC** [comment]
This is a good question and it would be good to have a consistent solution/guidance for this.

One option is in the right corner of the masthead with a simple icon and text link, with an additional skip-to link allowing people to skip to the "profile link" rather than past it.

Looking elsewhere,  the Carbon DS has the concept of a Global Header including utility links:

https://carbondesignsystem.com/patterns/global-header/#anatomy-of-a-global-header


food for thought!

**Comment by DFSIdigital** [comment]
Thank you for reaching out to us with your question about the addition of a profile icon and language selector in the upper part of the page on a mobile.

The placement of profile, search, and language selection links in the top navigation bar on a mobile device depends on various factors, including the overall design of your website or app and the user experience you want to achieve. While there isn't a definitive "best" practice, I can provide you with some commonly followed guidelines:

1. Hamburger Menu Approach: Placing profile, search, and language selection links within the main navigation drawer accessed via the hamburger menu is a popular approach. This helps keep the top navigation bar clean and uncluttered, providing a focused experience.
2. Right-aligned Links: Alternatively, you can place these links on the right side of the top navigation bar. This approach ensures that they are easily accessible and visible at all times. It can be particularly useful if you consider these links as primary actions or if they are frequently used by your users.

Ultimately, the decision depends on the specific needs and priorities of your application. Here are a few factors to consider:

- User Behaviour: Analyse how users interact with your website or app. If the profile, search, and language selection options are frequently used, you might want to consider keeping them more accessible.
- Screen Space: If the primary content and functionality of your app or website require the majority of the screen, using the hamburger menu for secondary actions can help declutter the interface.
- Consistency: Maintain consistency throughout your app or website. If you already have a hamburger menu for primary navigation, it might be more coherent to place the profile, search, and language selection links within it.

Ultimately, it's essential to conduct user testing or gather feedback from your target audience to determine which approach works best for your specific case.

Possible layout options (top one is very similar to nsw.gov.au, however, there is also an option to drop the logo and title below the top nav bar, making the action items less cluttered)

<img width="1033" alt="nav-mockup" src="https://github.com/digitalnsw/nsw-design-system/assets/47402941/b1788b21-ecb5-461d-b864-0faa6c9fbec5">

In hamburger display option

<img width="499" alt="nav-drawer" src="https://github.com/digitalnsw/nsw-design-system/assets/47402941/b5a57c0a-e362-4e0d-a848-1876726ab67e">

As for your side question regarding the Waratah logo with "Government" in the label versus the suggested blueprint with only "NSW" on mobile, it is generally acceptable to adapt the logo for mobile devices to ensure optimal visibility and legibility. The decision to remove the "Government" label in the mobile version can be made in order to maintain a clean and concise representation of the logo on smaller screens. However, it is important to maintain consistency and coherence across different platforms while adhering to the NSW Government branding guidelines.

Best regards,
Digital NSW Team

**Comment by eschweitzer78** [comment]
Thank you Digital NSW Team, really appreciate the very thorough and detailed answer. Love your work.
