### ISSUE TITLE
Shortcut classes for right-aligned items in the main navbar?

### ISSUE THREAD

**Issue by slead** [digitalnsw/nsw-design-system#392]
Hi there,

Are there any shortcut classes which I can use to right-align some components in the main navbar?

<img width="835" alt="Screenshot 2024-04-15 at 3 06 22 PM" src="https://github.com/digitalnsw/nsw-design-system/assets/133596/f83943ee-1cc2-4997-927b-be9429ddbc08">

I need to add these links to the top right of the navbar and would prefer not to use absolute positioning (etc) if there are any existing classes I should use instead.

thanks

**Comment by oisa** [comment]
Hi Stephen,

Thanks for reaching out here.

Completely understand the need to add in a right-aligned group of options for the main nav however at present, we don't have a variation or method within the component to fit in the "Log in | Sign up" CTAs that is clean and is easily adjusted - so it would need to be approached at this stage via absolute positioning (similar to how the search component is positioned despite you not utilising this feature) and may benefit from being represented via buttons instead of link options.

### Potential solution

Given it's not a variant in the header component, passing this by our UX/UI team and on from the above and looking at where is best to include the additional CTAs, they have advised that it would be more effective having them represented as buttons and positioned to the right of the search element within the `nsw-header__main` container instead (despite you not utilising the search element, you can see it included here: https://digitalnsw.github.io/nsw-design-system/components/main-nav/index.html), similar to below:

![additional-items-in-header](https://github.com/digitalnsw/nsw-design-system/assets/75308491/2c0f91dc-64fa-44aa-9a56-9556486a5ae6)

Noting the differentiation between the button types, giving weighting to the "Log in" option (Brand dark variant) following the Sign up option (Brand dark outline variant) - more information here: https://digitalnsw.github.io/nsw-design-system/components/button/index.html.

Positioning - at present, the cleanest inclusion would be to use a similar positioning method as the search component does (it does use absolute positioning which you can set via our utility classes: https://digitalnsw.github.io/nsw-design-system/docs/content/utilities/position.html).

### Multiple CTAs in the header in the NSW Design System

I will mention that we've put this on our list to make positioning extra elements in the header via flex and not absolutely.

Let me know if the above makes sense and you're able to find a solution in your context.

Thanks
